name: Secret Scanning (Reusable)

permissions: {}

on:
  workflow_call:
    inputs:
      branches:
        description: "Branches to trigger the workflow"
        required: false
        type: string
        default: "main,master"
      extra_args:
        description: "Extra arguments for TruffleHog"
        required: false
        type: string
        default: "--results=verified,unknown"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Trufflehog Secret Scanning
        uses: trufflesecurity/trufflehog@37b77001d0174ebec2fcca2bd83ff83a6d45a3ab # v3.95.3
        with:
          extra_args: ${{ inputs.extra_args }}
