name: 'Trunk Check'

description: 'Run trunk check on code that has been checked in'
runs:
  using: "composite"
  on: [pull_request, workflow_dispatch]
  steps: 

  - name: Checkout
    uses: actions/checkout@v3

  - name: Trunk Check
    uses: trunk-io/trunk-action@v1


# name: Pull Request
# concurrency:
#   group: ${{ github.head_ref || github.run_id }}
#   cancel-in-progress: true

# name: 'Trunk check on PR'
# description: 'Run trunk check'

# permissions: read-all