name: Trunk Nightly Upgrade
permissions: read-all

on:
  workflow_call:
    inputs:
      branch:
        description: The branch to upgrade
        required: false
        type: string
        default: master
      prefix:
        description: The prefix to use for commit messages
        required: false
        type: string
        default: 'infra: '
      token:
        description: The token to use for git operations
        required: false
        type: string
        default: ${{ github.token }}

jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write # For trunk to create PRs
      pull-requests: write # For trunk to create PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ inputs.token }}
      # >>> Install your own deps here (npm install, etc) <<<
      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v1
        with:
          base: ${{inputs.branch}}
          prefix: ${{inputs.prefix}}
